import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const supportedOutputExtension = ".webp";

export async function writeLocalProductImageIndex(projectRoot: string) {
  const imageDirectory = path.join(projectRoot, "public", "products");
  const outputPath = path.join(projectRoot, "data", "local-product-images.ts");

  let entries: string[] = [];

  try {
    entries = await readdir(imageDirectory);
  } catch {
    entries = [];
  }

  const slugs = entries
    .filter((fileName) => path.extname(fileName).toLowerCase() === supportedOutputExtension)
    .map((fileName) => path.basename(fileName, supportedOutputExtension))
    .sort((a, b) => a.localeCompare(b));

  const source = `// Generated by npm run images:index. Do not edit by hand.\n` +
    `export const localProductImageSlugs = new Set<string>(${JSON.stringify(slugs, null, 2)});\n\n` +
    `export function hasLocalProductImage(slug?: string): boolean {\n` +
    `  return Boolean(slug && localProductImageSlugs.has(slug));\n` +
    `}\n`;

  await writeFile(outputPath, source, "utf8");
  return { outputPath, count: slugs.length };
}
